set -o vi

alias vi='TERM=screen-bce vim'

export LANG=C

# Set the bash prompt
source ~/dev/mac/bash_prompt.sh

export MYSQL_PS1="\u@\d \R:\m:\s> "

# causes `ls` to color different types of contents (dir, executable, etc.).
export CLICOLOR=1

# Use Macports' GNU versions in favor of MacOS versions
export PATH=/opt/local/libexec/gnubin:$PATH

export GPG_TTY=$(tty)

DOT_FILE_PATH=~/dev/mac/dotFiles


###############################
#
# Python
#
###############################




